# Generated by Django 3.2 on 2023-11-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_rename_user_type_consultation_consultation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'CANCELLED')], default='pending', error_messages={'required': 'Please select a consultation status'}, max_length=20, verbose_name='Consultation Status'),
        ),
    ]
